name: flutter_om_jeweller
description: OM Jeweller Application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+8

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.2
  basic_utils: ^3.4.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  edge_alert: ^0.0.1
  dartx: ^1.0.0
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  shared_preferences: any
  lottie: ^1.2.1
  flutter_icons: ^1.1.0
  google_fonts: ^2.2.0
  stacked: ^2.2.1
  shimmer: ^2.0.0
  flutter_svg: ^1.0.0
  bottom_animation: ^2.0.0
  #chewie: ^1.2.2
  #video_player: ^2.2.10
  flutter_staggered_animations: ^1.0.0
  table_calendar: ^2.1.0
  dotted_line: ^3.1.0
  splashscreen: ^1.3.5
  google_maps_flutter: ^2.0.9
  url_launcher: ^6.0.17
  sms_autofill: ^2.2.0
  location: ^4.3.0
  location_permissions: ^4.0.1
  flutter_launcher_icons: ^0.9.2
  #youtube_player_flutter: ^8.0.0
  #pod_player: ^0.0.5

  #flutter_launcher_name: ^0.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

#flutter_launcher_name:
#  name: "OM Jewellers"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_white_bg.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  # Override path_provider to pick up fixes for FFI changes.
  path_provider: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
